### ISSUE TITLE
No puedo usar el administrador

### ISSUE THREAD

**Issue by Yoshivaleria** [alexaderramos/comercial-php#1]
He importado las dos bases de datos y la página funciona a la perfección para hacer altas de usuarios, pero por alguna razón no puedo ingresar como administrador, ¿hay alguna forma de solucionarlo?.

**Comment by alexaderramos** [comment]
Intenta colocando estas credenciales en el formulario de login.
Marcando la opción de Administrador
usuario: admin
contraseña: admin
